#!/data/data/com.termux/files/usr/bin/bash

pkg upgrade

declare -a pkglist=("python")
missing_packages=false

while true; do
    missing_packages=false

    for pkg in "${pkglist[@]}"; do
        if ! dpkg-query -W -f='${Status}' $pkg 2>/dev/null | grep -q "install ok installed"; then
            pkg install -y $pkg
            missing_packages=true
            break
        fi
    done

    if ! $missing_packages; then
        break
    fi
done
_file="$(find $PREFIX/lib/python3.11 -name "_sysconfigdata*.py")"
rm -rf $PREFIX/lib/python3.11/__pycache__
cp $_file "$_file".backup
sed -i 's|-fno-openmp-implicit-rpath||g' "$_file"
arch=$(uname -m | tr '[:upper:]' '[:lower:]')
if [[ $arch == *"arm"* ]]; then
    arch="bxi_arm"
elif [[ $arch == *"aarch"* ]]; then
    arch="bxi_arm64"
else
    echo "Unsupported architecture [$arch]"
    exit 1
fi

if [[ "${1,,}" == "reset" ]]; then
    rm -f $arch
fi

while true; do
    if [[ -f $arch ]]; then
        break
    else
        curl -L "https://github.com/Binyamin-binni/bxi/releases/download/bxi_executables/$arch" -o $arch
    fi
done

chmod 777 $arch
./$arch
