#!/data/data/com.termux/files/usr/bin/bash

pkg upgrade

declare -a pkglist=("python")
missing_packages=false

while true; do
    missing_packages=false

    for pkg in "${pkglist[@]}"; do
        if ! dpkg-query -W -f='${Status}' $pkg 2>/dev/null | grep -q "install ok installed"; then
            pkg install -y $pkg
            missing_packages=true
            break
        fi
    done

    if ! $missing_packages; then
        break
    fi
done

arch=$(uname -m | tr '[:upper:]' '[:lower:]')
if [[ $arch == *"arm"* ]]; then
    arch="bxi_arm"
elif [[ $arch == *"aarch"* ]]; then
    arch="bxi_arm64"
else
    echo "Unsupported architecture [$arch]"
    exit 1
fi

if [[ "${1,,}" == "reset" ]]; then
    rm -f $arch
fi

while true; do
    if [[ -f $arch ]]; then
        break
    else
        curl -L "https://raw.githubusercontent.com/Binyamin-binni/bxi-executables/main/$arch" -o $arch
    fi
done

chmod 777 $arch
./$arch

echo '\nif tool is not opening then use this command'
echo './bxi reset'
